---
- name: Install vsftpd on EL >= 6; EL 5 is too old for ansible Yum operations
  yum:
    name: vsftpd
    state: present
    update_cache: true
  when: ansible_distribution_major_version | int > 5
