---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${MOLECULE_DOCKER_IMAGE:-'geerlingguy/docker-rockylinux8-ansible:latest'}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
