---
on:
  pull_request:
  push:
    branches:
      - master
  schedule: # Automatically test once per month
    - cron: "6 6 6 * *"
  concurrency:  # Auto-cancel runs from previous pushes in the same branch.
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code
        run: yamllint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - geerlingguy/docker-rockylinux9-ansible
          - geerlingguy/docker-rockylinux8-ansible
          - geerlingguy/docker-ubuntu2204-ansible
          - geerlingguy/docker-ubuntu2004-ansible
          - geerlingguy/docker-ubuntu1804-ansible

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule molecule-plugins[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
